include:
  - path: plex/docker-compose.yml
  - path: jellyfin/docker-compose.yml
  - path: tautulli/docker-compose.yml
  - path: maintainerr/docker-compose.yml
  - path: posterizarr/docker-compose.yml
