services:
  kapowarr:
    image: mrcas/kapowarr:latest
    container_name: kapowarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${KAPOWARR_PORT}:5656"
    volumes:
      - "./config/db:/app/db"
      - "${KAPOWARR_TEMP_DOWNLOADS_DIR}:/app/temp_downloads"
      - "${KAPOWARR_COMICS_DIR}:/comics"
    restart: unless-stopped
