services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - TZ=${TZ}
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
    ports:
      - "${JDOWNLOADER_PORT}:5800"
    volumes:
      - "./config:/config"
      - "${STORAGE_DIR}/downloads/jdownloader:/output"
    restart: unless-stopped
