services:
  aggregarr:
    image: agregarr/agregarr:latest
    container_name: aggregarr
    environment:
      - TZ=${TZ}
    ports:
      - "${AGGREGARR_PORT}:7171"
    volumes:
      - "./config/aggregarr:/app/config"
    restart: unless-stopped
