services:
  boxarr:
    image: ghcr.io/iongpt/boxarr:latest
    container_name: boxarr
    environment:
      - TZ=${TZ}
    ports:
      - "${BOXARR_PORT}:8888"
    volumes:
      - "./config/boxarr:/config"
    restart: unless-stopped
