include:
  - path: prowlarr/docker-compose.yml
  - path: radarr/docker-compose.yml
  - path: sonarr/docker-compose.yml
  - path: lidarr/docker-compose.yml
  - path: whisparr/docker-compose.yml
  - path: kapowarr/docker-compose.yml
  - path: bazarr/docker-compose.yml
  - path: flaresolverr/docker-compose.yml
  - path: linkarr/docker-compose.yml
  - path: boxarr/docker-compose.yml
  - path: aggregarr/docker-compose.yml
