services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - '7008:8191'
    volumes:
      - ${PROXMOX_DIR}/appdata/flaresolverr:/config
    restart: unless-stopped
