services:
  linkarr:
    image: itsmejoeeey/linkarr:latest
    container_name: linkarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${LINKARR_PORT}:8080"
    volumes:
      - "./config/linkarr/config.json:/config/config.json"
      - "${LINKARR_SOURCE_DIR}:${LINKARR_SOURCE_DIR}"
      - "${LINKARR_ORGANIZED_DIR}:${LINKARR_ORGANIZED_DIR}"
    restart: unless-stopped
