services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${PROWLARR_PORT}:9696"
    volumes:
      - "./config/prowlarr:/config"
    restart: unless-stopped
