services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${FLARESOLVERR_PORT}:8191"
    volumes:
      - "./config:/config"
    restart: unless-stopped
