include:
  - path: gluetun/docker-compose.yml
  - path: qbittorrent/docker-compose.yml
  - path: sabnzbd/docker-compose.yml
  - path: jdownloader/docker-compose.yml
  - path: metube/docker-compose.yml
  - path: immich-drop/docker-compose.yml
