services:
  immich-drop:
    image: aslami/immich-drop:latest
    container_name: immich-drop
    environment:
      - TZ=${TZ}
    ports:
      - '5006:8080'
    volumes:
      - ${PROXMOX_DIR}/appdata/immich-drop:/config
      - ${STORAGE_DIR}/photos:/photos
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
