services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
      - WEBUI_PORT=8080
    volumes:
      - ${PROXMOX_DIR}/appdata/qbittorrent:/config
      - ${STORAGE_DIR}:/storage
    restart: unless-stopped
