services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${SABNZBD_PORT}:8080"
    volumes:
      - "./config:/config"
      - "${STORAGE_DIR}:/storage"
    restart: unless-stopped
