services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${METUBE_PORT}:8081"
    volumes:
      - "./config:/config"
      - "${STORAGE_DIR}/downloads/metube:/downloads"
    restart: unless-stopped
