services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - TZ=${TZ}
      - DOZZLE_HOSTNAME=${HOSTNAME}
    ports:
      - '11002:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
