services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - TZ=${TZ}
    ports:
      - '11001:3001'
    volumes:
      - ${PROXMOX_DIR}/appdata/uptime-kuma:/app/data
    restart: unless-stopped
