include:
  - path: homepage/docker-compose.yml
  - path: jellyseerr/docker-compose.yml
  - path: wizarr/docker-compose.yml
  - path: speedtest/docker-compose.yml
  - path: changedetection/docker-compose.yml
  - path: filebrowser/docker-compose.yml
