services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - TZ=${TZ}
    ports:
      - '6006:8080'
    volumes:
      - ${PROXMOX_DIR}/appdata/filebrowser:/config
      - ${STORAGE_DIR}:/srv
    restart: unless-stopped
