services:
  immich-drop:
    image: aslami/immich-drop:latest
    container_name: immich-drop
    environment:
      - TZ=${TZ}
    ports:
      - "${IMMICH_DROP_PORT}:8080"
    volumes:
      - "./config:/config"
      - "${STORAGE_DIR}/photos:/photos"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
